/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arthur' at '17. 6. 12 오전 11:14' with Gradle 2.14.1
 *
 * @author Arthur, @date 17. 6. 12 오전 11:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
